# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G

# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version = b1.7.3
loader_version = 0.15.6-babric.1
mappings = 0.1.1

# Mod Properties
mod_version = 1.0.0-alpha
maven_group = paulevs.bnb
archives_base_name = bnb

# Dependencies
stapi_version = 2.0.0-alpha.3
bhcreative_version = 0.4.8
vbe_version = 0.2.6
retrocommands_version = 0.5.4
