# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G

# Fabric Properties
# check these on https://fabricmc.net/use
minecraft_version = b1.7.3
loader_version = 0.16.9
mappings = 0.1.1

# Mod Properties
mod_version = 1.0.0-alpha-9
maven_group = paulevs.bnb
archives_base_name = bnb

# Dependencies
stapi_version = 2.0.0-alpha.5.1
bhcreative_version = 0.4.9
vbe_version = 0.2.18
materialexcavator_version=0.3.0
retrocommands_version = 0.5.4
alwaysmoreitems_version = 1.6.0
glass_networking_version=1.0.6
gcapi_version=3.2.1
